language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - python -m pip install -r requirements.txt -r requirements-test.txt
script:
  - python -m pytest tests/ --cov coollect --cov-report html:coverage